# fly.toml docs and default values at https://fly.io/docs/reference/configuration/

app = "tailnet-dns"
primary_region = "ews"

# TS_AUTHKEY specified in fly secrets

[[mounts]]
  source = "ipn_dns_root"
  destination = "/root"

[[services]]
  protocol = "udp"
  internal_port = 53

  [[services.ports]]
    port = 53
