app = "willnorris-ipn-dns"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

# TS_AUTHKEY specified in fly secrets

[[mounts]]
  source = "ipn_dns_root"
  destination = "/root"

[[services]]
  protocol = "udp"
  internal_port = 53

  [[services.ports]]
    port = 53
